### ISSUE TITLE
Local Build Failed w/ no config.h

### ISSUE THREAD

**Issue by rbogdan** [maxlab-io/tokay-lite-sdk#6]
Hi , I am trying to build tokay lite using a local install on an orangepi5 with bookworm v12. I've downloaded and installed esp-idf v5.4.
I am able to build their examples. When I try to build tokay lite the build fails with a missing config.h file.  I'm hoping someone can give me a clue, I think it must be a step I'm missing.

The steps I took after downloading tokay and the submodule updates are as follows:
cd ~/tokay-lite-sdk/
. $HOME/esp/esp-idf/export.sh
cd webserver
idf.py set-target esp32s3
cd ~/tokay-lite-sdk/
idf.py build -C webserver

Everything up to the build command works without error. The build fails with the following (I've attached the idf_py_stdout_output_21546 file):

Missing "config.h" file name found in the following component(s): bt(/home/orangepi/esp/esp-idf/components/bt/common/osi/include/osi/config.h), bt(/home/orangepi/esp/esp-idf/components/bt/esp_ble_mesh/common/include/mesh/config.h), lwip(/home/orangepi/esp/esp-idf/components/lwip/lwip/test/apps/config.h), lwip(/home/orangepi/esp/esp-idf/components/lwip/lwip/test/fuzz/config.h), openthread(/home/orangepi/esp/esp-idf/components/openthread/openthread/include/openthread/config.h). Maybe one of the components needs to add the missing header directory to INCLUDE_DIRS of idf_component_register call in CMakeLists.txt.
[idf_py_stdout_output_21546.zip](https://github.com/user-attachments/files/16645998/idf_py_stdout_output_21546.zip)

**Comment by forGGe** [comment]
I've just merged #7, which migrates the SDK to v5.3. Can you try building the FW against IDF v5.3? 
Docs will follow, soon

**Comment by rbogdan** [comment]
This resolved my build issue, thank you very much!
